[workspace]
members = [
  "app",
  "crates/core"
]
exclude = [
  "refs/crates"
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92.0"
license = "AGPL-3.0"

[workspace.dependencies]
leptos = { version = "0.8.5", default-features = false }
wasm-bindgen = "=0.2.100"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
getrandom = "0.2"
js-sys = "0.3.77"
web-sys = { version = "0.3.77", features = [
  "Crypto",
  "CryptoKey",
  "SubtleCrypto",
  "Window",
  "Document",
  "Element",
  "DomException",
  "DomStringList",
  "Event",
  "EventTarget",
  "File",
  "FileList",
  "FileReader",
  "HtmlInputElement",
  "IdbDatabase",
  "IdbFactory",
  "IdbObjectStore",
  "IdbOpenDbRequest",
  "IdbRequest",
  "IdbTransaction",
  "IdbTransactionMode",
  "Coordinates",
  "Geolocation",
  "Navigator",
  "Notification",
  "NotificationOptions",
  "NotificationPermission",
  "PermissionDescriptor",
  "PermissionName",
  "PermissionState",
  "PermissionStatus",
  "Permissions",
  "Position",
  "PositionError",
  "PositionOptions",
] }
wasm-bindgen-futures = "0.4"
base64 = "0.22"
serde-wasm-bindgen = "0.6"
rusqlite = { version = "0.31", default-features = false }
radroots-nostr = { path = "refs/crates/nostr" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[profile.wasm-release]
inherits = "release"
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
